---
title: "RWorksheet_Gallenero#4a"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. Create a data frame
df_shoe <- data.frame(
                 Shoe_Size=c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 
                             10.5,8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5,
                             7.5, 8.5, 10.5, 8.5,10.5, 11.0, 9.0, 13.0),
                Height=c(66.0, 68.0, 64.5, 65.0, 70.0,64.0, 70.0, 71.0, 72.0, 64.0,74.5, 
                         67.0,71.0, 71.0,77.0, 72.0, 59.0, 62.0, 72.0,66.0, 64.0, 
                         67.0,73.0, 69.0, 72.0, 70.0,69.0, 70.0),
                Gender= c( "F", "F", "F", "F", "M", "F","F","F", "M", "F", "M", 
                           "F","M", "M","M", "M", "F","F", "M", "F", "F", "M","M",
                           "F", "M", "M", "M","M"))
df_shoe

#a.
# This data set includes information about each person's # height, shoe size, and gender.

#b. 
female_subset <- df_shoe[df_shoe$Gender == "F", c("Gender", "Shoe_Size", "Height")]
female_subset

male_subset <- df_shoe[df_shoe$Gender == "M", c("Gender", "Shoe_Size", "Height")]
male_subset

# c.
mean_shoesize <- mean(df_shoe$Shoe_Size)
mean_shoesize
mean_height <- mean(df_shoe$Height)
mean_height

# d.
# The relationship between the two is that height and shoe size are directly proportional. A short height corresponds to a small shoe size.

#2. Constructing the character vector months

months_vector <-c("March","April","January","November","January", "September", "October", "September", "November","August", "January", "November", "November", "February", "May", "August","July", "December","August","August","September","November","February","April")                                

# Converting the character vector months to a factor
factor_months_vector <- factor(months_vector)
factor_months_vector

#3

summary(months_vector)
summary(factor_months_vector)

#4

Direction <- c ("East", "West", "North")
Direction
Frequency <- c (1,4,3)
Frequency 

factor_data <- factor (c(Direction, Frequency))
factor_data

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)

#5
import_table <- read.table(file =  "/cloud/project/worksheet#4/import_march.csv", header = TRUE, sep = ",")

import_table

#6 
random_num <- readline(prompt = "Enter number from 1 to 50: ")

#cant knit if there is as.numeric
#random_num <- as.numeric(random_num)

paste("The number you have chosen is", random_num)

if (random_num > 50) {
  paste("The number selected is beyond the range of 1 to 50")
} else if (random_num == 20) {
  paste("TRUE")
} else {
  paste(random_num)
}

#7
minimumBills <- function(price) {
  
  minBills <- price %/% 50
  paste("The minimum no. of bills:", minBills)
}

minimumBills(90)

#8

names <- c("Annie", "Thea", "Steve", "Hanna")
grade1 <- c(85,65,75,95)
grade2 <- c(65,75,55,75)
grade3 <- c(85,90,80,100)
grade4 <- c(100,90,85,90)

grade <- data.frame(
  Name = names,
  Grade1 = grade1,
  Grade2 = grade2,
  Grade3 = grade3,
  Grade4 = grade4
)
grade
# 8.b

grade$Average <- (grade$Grade1 + grade$Grade2 + grade$Grade3 + grade$Grade4) / 4

highScorers <- grade[grade$Average > 90,]
highScorers

if (nrow(highScorers) > 0) {
  paste(highScorers$Name, "'s average grade this semester is", highScorers$Average)
} else {
  paste("No students have an average math score over 90.")
}

# 8.c

first_test <- sum(grade$Grade1) / nrow(grade)
first_test

second_test <- sum(grade$Grade2) / nrow(grade)
second_test

third_test <- sum(grade$Grade3) / nrow(grade)
third_test

fourth_test <- sum(grade$Grade4) / nrow(grade)
fourth_test

if (first_test < 80) {
  paste("The 1st test was difficult.")
} else if(second_test < 80) {
  paste("The 2nd test was difficult.")
} else if(third_test < 80) {
  paste("The 3rd test was difficult.")
} else if(fourth_test < 80) {
  paste("The 4th test was difficult.")
} else {
  paste("No test had an average score less than 80.")
}

# Annie
if (grade[1,2] > grade[1,3] && grade[1,2] > grade[1,4] && grade[1,2] > grade[1,5]) {
  annieHighest <- grade[1,2]
} else if (grade[1,3] > grade[1,4] && grade[1,3] > grade[1,5]) {
  annieHighest <- grade[1,3]
} else if (grade[1,4] > grade[1,5] && grade[1,2] > grade[1,5]) {
  annieHighest <- grade[1,4]
} else {
  annieHighest <- grade[1,5]
}


# Thea
if (grade[2,2] > grade[2,3] && grade[2,2] > grade[2,4] && grade[2,2] > grade[2,5]) {
  theaHighest <- grade[2,2]
} else if (grade[2,3] > grade[2,4] && grade[2,3] > grade[2,5]) {
  theaHighest <- grade[2,3]
} else if (grade[2,4] > grade[2,5] && grade[2,2] > grade[2,5]) {
  theaHighest <- grade[2,4]
} else {
  theaHighest <- grade[2,5]
}
# Steve
if (grade[3,2] > grade[3,3] && grade[3,2] >grade[3,4] && grade[3,2] > grade[3,5]) {
  steveHighest <- grade[3,2]
} else if (grade[3,3] > grade[3,4] && grade[3,3] >grade[3,5]) {
  steveHighest <- grade[2,3]
} else if (grade[3,4] > grade[3,5] && grade[3,2] > grade[3,5]) {
  steveHighest <- grade[3,4]
} else {
  steveHighest <- grade[3,5]
}

# Hanna
if (grade[4,2] > grade[4,3] && grade[4,2] > grade[4,4] && grade[4,2] > grade[4,5]) {
  hannaHighest <- grade[4,2]
} else if (grade[4,3] > grade[4,4] && grade[4,3] > grade[4,5]) {
  hannaHighest <- grade[2,3]
} else if (grade[4,4] > grade[4,5] && grade[4,2] > grade[4,5]) {
  hannaHighest <- grade[4,4]
} else {
  hannaHighest <- grade[4,5]
}

grade$HighestGrades <- c(annieHighest, theaHighest, steveHighest, hannaHighest)


above90 <- grade[grade$HighestGrades > 90,]
above90

if (nrow(above90) > 0) {
  paste(above90$Name, "'s highest grade this semester is", above90$HighestGrade)
} else {
  paste("No students have an average math score over 90.")
}


```