---
title: "RWorksheet_Gallenero#4a"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

df_shoe <- data.frame(
                Shoe_Size=c(6.5, 9.0, 8.5, 8.5, 10.5,                    7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5,                     12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0,                  6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0,                    9.0, 13.0),

              
                Height=c(66.0, 68.0, 64.5, 65.0, 70.0,                   64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0,                 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0,                 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0,                 69.0, 70.0),
                
                Gender= c( "F", "F", "F", "F", "M", "F",                 "F","F", "M", "F", "M", "F", "M", "M",                   "M", "M", "F", "F", "M", "F", "F", "M",                  "M", "F", "M", "M", "M", "M"),


df_shoe
#a.
# This data set includes information about each person's # height, shoe size, and gender.

# b. 
subset_male <- subset(df_shoe, Gender == 'M')
subset_female <- subset(df_shoe, Gender == 'F')
subset_male
subset_female

# c.
mean_shoesize <- mean(df_shoe$Shoe_Size)
mean_shoesize
mean_height <- mean(df_shoe$Height)
mean_height

# Constructing the character vector months

months_vector <-c("March","April","January","November",                    "January", "September", "October",   "September",                  "November","August", "January", "November",               "November", "February", "May", "August",                "July", "December",                       "August","August","September","November","February", "April")
# Converting the character vector months to a factor
factor_months_vector <- factor(months_vector)
factor_months_vector

# 3. 

summary(months_vector)
summary(factor_months_vector)

# 4.

Direction <- c ("East", "West", "North")
Direction
Frequency <- c (1,4,3)
Frequency 

factor_data <- factor (c(direction, frequency))
factor_data

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)

#5